# App store metadata
app:
  primary_category: "UTILITIES"
  secondary_category: "PRODUCTIVITY"
  # name: "App"
  # locales: # keys like "fr-FR" can contain localized description, name, etc.

# Pages / Jekyll configuration::
remote_theme: appfair/fairapp-theme

