# Marketplace metadata
deliver:
  # name: App
  subtitle: A really great App Fair app
  promotional_text: Be the first to download this app!
  description: A simple app fair app.
  keywords: appfair
  primary_category: UTILITIES
  secondary_category: PRODUCTIVITY
  locale:
    en-US:
      description: A simple app fair app.
    fr:
      name: Le App
      description: Une app simple.

# Configuration for GitHub Pages / Jekyll follows:
remote_theme: appfair/fairapp-theme

